name: "Assignment 1"

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                cd SimpleApp
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: SimpleApp
                path: SimpleApp
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: SimpleApp
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Deploy to AWS EC2
              run: |
                echo "Deploying to AWS EC2"